config/routes.rb
Houndapp::Application.routes.draw do
  mount Resque::Server, at: "/queue"
  mount StripeEvent::Engine => "/stripe-event"
  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)

  get "/auth/github/callback", to: "sessions#create"
  get "/sign_out", to: "sessions#destroy"
  get "/configuration", to: "application#configuration"
  get "/faq", to: "pages#show", id: "faq"

  resource :account, only: [:show]
  resources :builds, only: [:create]
  resource :credit_card, only: [:update]

  resources :repos, only: [:index] do
    resource :activation, only: [:create]
    resource :deactivation, only: [:create]
    resource :subscription, only: [:create, :destroy]
  end

  resources :repo_syncs, only: [:index, :create]
  resource :user, only: [:show]

  root to: "home#index"
end

app/views/shared/_footer.haml
%footer.app-footer
  %p
    Hound is maintained by #{link_to 'thoughtbot', 'http://thoughtbot.com'}.
    Questions? Try the
    #{link_to 'FAQ', faq_path} or
    Tweet #{link_to '@houndci', 'https://twitter.com/houndci'}.

  %p
    Hound is Copyright &copy; #{Date.today.year} thoughtbot. It is open source
    software and may be redistributed under the terms specified in the
    #{link_to 'LICENSE', 'https://github.com/thoughtbot/hound/blob/master/LICENSE'}.

  %ul.links
    %li
      = link_to "Source Code", "https://github.com/thoughtbot/hound"
    %li
      = link_to "FAQ", faq_path
    %li
      = link_to "Terms", "https://github.com/thoughtbot/hound/blob/master/doc/TERMS.md"
    %li
      = link_to "Privacy", "https://github.com/thoughtbot/hound/blob/master/doc/PRIVACY.md"
    %li
      = link_to "Security", "https://github.com/thoughtbot/hound/blob/master/doc/SECURITY.md"

app/views/shared/_header.haml
%header
  %ul.pull-left
    %li
      = link_to repos_path, class: "logo" do
        %h1 Hound
    %li
      = link_to "Docs", configuration_path, class: "docs"
    %li
      = link_to "FAQ", faq_path, class: "faq"
  - if signed_in?
    %ul.pull-right
      %li
        = link_to account_path, class: "account" do
          - if current_user.email_address.present?
            .avatar(style="background-image: url('#{avatar_url(current_user)}')")
          %span #{current_user.github_username}
      %li
        = link_to "Sign Out", sign_out_path, class: "sign-out"